create table account_user
(
    id          bigint generated by default as identity,
    created_at  timestamp not null,
    modified_at timestamp,
    version     integer,
    birthday    date,
    email       varchar(255),
    first_name  varchar(255),
    last_name   varchar(255),
    login       varchar(255),
    password    varchar(255),
    phone       varchar(255),
    primary key (id),
    constraint uk_email_account_user unique (email),
    constraint uk_login_account_user unique (login)
);

create table car
(
    id              bigint generated by default as identity,
    created_at      timestamp not null,
    modified_at     timestamp,
    version         integer,
    color           varchar(255),
    license_plate   varchar(255),
    model           varchar(255),
    production_year integer,
    usage_count     integer,
    account_user_id bigint,
    primary key (id),
    foreign key (account_user_id) references account_user (id)
);
