create table account_user
(
    id          int8 generated by default as identity,
    created_at  timestamp not null,
    modified_at timestamp,
    version     int4,
    birthday    date,
    email       varchar(255),
    first_name  varchar(255),
    last_name   varchar(255),
    login       varchar(255),
    password    varchar(255),
    phone       varchar(255),
    primary key (id),
    constraint uk_email_account_user unique (email),
    constraint uk_login_account_user unique (login)
)

create table car
(
    id              int8 generated by default as identity,
    created_at      timestamp not null,
    modified_at     timestamp,
    version         int4,
    color           varchar(255),
    license_plate   varchar(255),
    model           varchar(255),
    production_year int4,
    usageCount      int4,
    primary key (id)
)

alter table car
    add constraint fk_car_account_user
        foreign key (account_user_id)
            references account_user